const fs = require('fs');
const lines = [
"'use client';",
"",
"import Link from 'next/link';",
"import { useLanguage } from '@/context/LanguageContext';",
"import { translations } from '@/lib/translations';",
"import { WA_BASE } from '@/lib/constants';",
"import { Shield, BarChart, Zap } from 'lucide-react';",
"",
"export default function BerandaPage() {",
"  const { lang } = useLanguage();",
"  const t = translations[lang].beranda;",
"  return (",
"    <div className=\"min-h-screen bg-navy overflow-x-hidden\">",
"      <section className=\"relative px-5 pt-20 pb-20 bg-line-grid\">",
"        <div className=\"max-w-4xl mx-auto text-center relative z-10\">",
"          <h1 className=\"font-syne font-extrabold leading-[1.05] mb-6\">",
"            <span className=\"block text-4xl sm:text-6xl lg:text-7xl text-white\">{t.title1}</span>",
"            <span className=\"block text-4xl sm:text-6xl lg:text-7xl text-primary glow-cyan\">{t.title2}</span>",
"          </h1>",
"          <p className=\"font-mono text-sm text-gray-400 max-w-2xl mx-auto mb-10\">{t.subtitle}</p>",
"          <div className=\"flex flex-col sm:flex-row items-center justify-center gap-3\">",
"            <Link href=\"/harga\" className=\"font-mono text-[12px] font-bold bg-primary text-navy px-8 py-3.5 rounded\">{t.cta}</Link>",
"            <Link href=\"/roi\" className=\"font-mono text-[12px] border border-white/15 text-gray-300 px-8 py-3.5 rounded\">{t.ctaDemo}</Link>",
"          </div>",
"        </div>",
"      </section>",
"      <section className=\"border-y border-white/5 bg-card\">",
"        <div className=\"max-w-5xl mx-auto px-5 py-6 grid grid-cols-2 lg:grid-cols-4 gap-6\">",
"          {t.statsLabel.map((label, i) => (",
"            <div key={i} className=\"text-center\">",
"              <div className=\"font-syne font-extrabold text-2xl text-primary mb-1\">{t.statsValue[i]}</div>",
"              <div className=\"font-mono text-[10px] text-gray-500 uppercase\">{label}</div>",
"            </div>",
"          ))}",
"        </div>",
"      </section>",
"      <section className=\"px-5 py-24\">",
"        <div className=\"max-w-6xl mx-auto\">",
"          <div className=\"text-center mb-14\">",
"            <span className=\"font-mono text-[11px] text-primary/70 uppercase\">Core Capabilities</span>",
"            <h2 className=\"font-syne font-bold text-3xl sm:text-4xl text-white mt-3\">{t.featTitle}</h2>",
"          </div>",
"          <div className=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4\">",
"            {t.features.map((feat, i) => (",
"              <div key={i} className=\"group border border-white/6 bg-card rounded-xl p-6\">",
"                <div className=\"w-11 h-11 rounded-lg bg-primary/8 border border-primary/15 flex items-center justify-center mb-5\">",
"                  {feat.icon === 'Shield' && <Shield size={22} className=\"text-primary\" />}",
"                  {feat.icon === 'BarChart' && <BarChart size={22} className=\"text-primary\" />}",
"                  {feat.icon === 'Zap' && <Zap size={22} className=\"text-primary\" />}",
"                </div>",
"                <h3 className=\"font-syne font-bold text-white text-[15px] mb-2\">{feat.title}</h3>",
"                <p className=\"font-mono text-[11px] text-gray-500\">{feat.desc}</p>",
"              </div>",
"            ))}",
"          </div>",
"        </div>",
"      </section>",
"      <section className=\"px-5 pb-24\">",
"        <div className=\"max-w-3xl mx-auto text-center bg-card rounded-2xl p-12\">",
"          <h2 className=\"font-syne font-bold text-3xl text-white mb-3\">{t.cta2Title}</h2>",
"          <p className=\"font-mono text-sm text-gray-400 mb-8\">{t.cta2Subtitle}</p>",
"          <a href={WA_BASE} target=\"_blank\" rel=\"noopener noreferrer\" className=\"font-mono text-[12px] font-bold bg-primary text-navy px-10 py-3.5 rounded inline-block\">{t.cta2Btn}</a>",
"        </div>",
"      </section>",
"    </div>",
"  );",
"}",
];
require('fs').writeFileSync('app/page.tsx', lines.join('\n'), 'utf8');
console.log('DONE');